# Generated by Django 2.2.4 on 2019-08-08 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ethnic_national_ids',
        ),
        migrations.AddField(
            model_name='profile',
            name='identities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=3),
        ),
    ]
