# Generated by Django 2.2.4 on 2019-08-08 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly', '0002_auto_20190808_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=3),
        ),
    ]
