# Generated by Django 2.2.4 on 2019-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly', '0004_match_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.PositiveIntegerField(default=94103, max_length=5),
            preserve_default=False,
        ),
    ]
