# Generated by Django 2.2.4 on 2019-08-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly', '0006_auto_20190808_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='blank-profile-picture.jpg', null=True, upload_to='images/'),
        ),
    ]
