# Generated by Django 2.2.4 on 2019-08-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly', '0007_auto_20190809_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/blank-profile-picture.png', null=True, upload_to='images/'),
        ),
    ]
